# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pubsub.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cpubsub.proto\"\t\n\x07Request\" \n\tthemeList\x12\x13\n\x0btheme_index\x18\x01 \x03(\x05\"\x1c\n\x05theme\x12\x13\n\x0btheme_index\x18\x01 \x01(\x05\"0\n\x03pub\x12\x1b\n\x0btheme_index\x18\x01 \x01(\x0b\x32\x06.theme\x12\x0c\n\x04text\x18\x02 \x01(\t2\x87\x01\n\x06pubsub\x12\"\n\x08getTheme\x12\x08.Request\x1a\n.themeList\"\x00\x12\x1d\n\tsubscribe\x12\x06.theme\x1a\x06.theme\"\x00\x12\x1f\n\x0b\x63reateTheme\x12\x06.theme\x1a\x06.theme\"\x00\x12\x19\n\x07publish\x12\x04.pub\x1a\x06.theme\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pubsub_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_REQUEST']._serialized_start=16
  _globals['_REQUEST']._serialized_end=25
  _globals['_THEMELIST']._serialized_start=27
  _globals['_THEMELIST']._serialized_end=59
  _globals['_THEME']._serialized_start=61
  _globals['_THEME']._serialized_end=89
  _globals['_PUB']._serialized_start=91
  _globals['_PUB']._serialized_end=139
  _globals['_PUBSUB']._serialized_start=142
  _globals['_PUBSUB']._serialized_end=277
# @@protoc_insertion_point(module_scope)
